---
- name: Run Jenkins setup
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: List directories in roles path
      command: ls -R /home/ubuntu/.ansible/pull/{{ inventory_hostname }}/ansible-run/roles/
      register: result
      ignore_errors: yes

    - name: Print directory listing
      debug:
        msg: "{{ result.stdout_lines }}"

    
    - include_role:
        name: "{{ role_name }}"




  # 225  sudo apt-add-repository ppa:ansible/ansible
  # 226  sudo apt update -y
  # 227  sudo apt install ansible
  # 228  ansible --version

